### ISSUE TITLE
How to handle send chat message from server SDK, and then client retrieve it

### ISSUE THREAD

**Issue by teoprayoga** [livekit-examples/meet#69] opened 2023-05-07 01:34 UTC

**Comment by lukasIO** [comment] 2023-05-08 15:44
hi @teoprayoga , 
generally you will want to use one of the livekit server sdks (the one in this repo is used e.g. in the `/api/token` endpoint) and construct a data message from there with the topic `lk-chat`.  https://docs.livekit.io/server-sdk-js/classes/RoomServiceClient.html#sendData

feel free to ask more about it on our [community slack](https://join.slack.com/t/livekit-users/shared_invite/zt-rrdy5abr-5pZ1wW8pXEkiQxBzFiXPUg), I will close the issue here, as it's not a bug, but rather a support question.

**Closed by lukasIO** 2023-05-08 15:44 UTC
